config/routes.rb
C2earthDev::Application.routes.draw do
  resources :investigation_types

  resources :structure_types

  resources :sites

  resources :faults

  resources :projects

  resources :stakeholder_types

  resources :companies

  resources :stakeholders

  resources :client_types

  resources :project_managers

  resources :phases

  resources :projects
  root :to => 'projects#index'

end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base
  attr_accessible :address, :address_alternate, :cell_phone, :cell_phone_alternate, :city, :city_alternate, :client_type_id, :company_id, :email, :email_alternate, :fax_phone, :fax_phone_alternate, :home_phone, :home_phone_alternate, :name, :name, :notes, :stakeholder_type_id, :state, :state_alternate, :work_phone, :work_phone_alternate, :zip, :zip_alternate
  belongs_to :company
  has_and_belongs_to_many :stakeholder_types
  belongs_to :client_type
end

app/models/stakeholder_type.rb
class StakeholderType < ActiveRecord::Base
  attr_accessible :stakeholder_type
  has_and_belongs_to_many :stakeholders
end

app/controllers/stakeholders_controller.rb
class StakeholdersController < ApplicationController
  # GET /stakeholders
  # GET /stakeholders.json
  def index
    @stakeholders = Stakeholder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stakeholders }
    end
  end

  # GET /stakeholders/1
  # GET /stakeholders/1.json
  def show
    @stakeholder = Stakeholder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stakeholder }
    end
  end

  # GET /stakeholders/new
  # GET /stakeholders/new.json
  def new
    @stakeholder = Stakeholder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stakeholder }
    end
  end

  # GET /stakeholders/1/edit
  def edit
    @stakeholder = Stakeholder.find(params[:id])
  end

  # POST /stakeholders
  # POST /stakeholders.json
  def create
    @stakeholder = Stakeholder.new(params[:stakeholder])

    respond_to do |format|
      if @stakeholder.save
        format.html { redirect_to @stakeholder, notice: 'Stakeholder was successfully created.' }
        format.json { render json: @stakeholder, status: :created, location: @stakeholder }
      else
        format.html { render action: "new" }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stakeholders/1
  # PUT /stakeholders/1.json
  def update
    @stakeholder = Stakeholder.find(params[:id])

    respond_to do |format|
      if @stakeholder.update_attributes(params[:stakeholder])
        format.html { redirect_to @stakeholder, notice: 'Stakeholder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stakeholders/1
  # DELETE /stakeholders/1.json
  def destroy
    @stakeholder = Stakeholder.find(params[:id])
    @stakeholder.destroy

    respond_to do |format|
      format.html { redirect_to stakeholders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/stakeholders/_form.html.haml
= form_for @stakeholder do |f|
  - if @stakeholder.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stakeholder.errors.count, "error")} prohibited this stakeholder from being saved:"
      %ul
        - @stakeholder.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :stakeholder_type_id
    = f.number_field :stakeholder_type_id
  .field
    = f.label :company_id
    = f.number_field :company_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :client_type_id
    = f.text_field :client_type_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip
    = f.number_field :zip
  .field
    = f.label :work_phone
    = f.text_field :work_phone
  .field
    = f.label :home_phone
    = f.text_field :home_phone
  .field
    = f.label :cell_phone
    = f.text_field :cell_phone
  .field
    = f.label :fax_phone
    = f.text_field :fax_phone
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :address_alternate
    = f.text_field :address_alternate
  .field
    = f.label :city_alternate
    = f.text_field :city_alternate
  .field
    = f.label :state_alternate
    = f.text_field :state_alternate
  .field
    = f.label :zip_alternate
    = f.number_field :zip_alternate
  .field
    = f.label :work_phone_alternate
    = f.text_field :work_phone_alternate
  .field
    = f.label :home_phone_alternate
    = f.text_field :home_phone_alternate
  .field
    = f.label :cell_phone_alternate
    = f.text_field :cell_phone_alternate
  .field
    = f.label :fax_phone_alternate
    = f.text_field :fax_phone_alternate
  .field
    = f.label :email_alternate
    = f.text_field :email_alternate
  .field
    = f.label :notes
    = f.text_area :notes
  .actions
    = f.submit 'Save'

app/views/stakeholders/edit.html.haml
%h1 Editing stakeholder

= render 'form'

= link_to 'Show', @stakeholder
\|
= link_to 'Back', stakeholders_path

app/views/stakeholders/index.html.haml
%h1 Listing stakeholders

%table
  %tr
    %th Stakeholder type
    %th Company
    %th Name
    %th Client type
    %th Name
    %th Address
    %th City
    %th State
    %th Zip
    %th Work phone
    %th Home phone
    %th Cell phone
    %th Fax phone
    %th Email
    %th Address alternate
    %th City alternate
    %th State alternate
    %th Zip alternate
    %th Work phone alternate
    %th Home phone alternate
    %th Cell phone alternate
    %th Fax phone alternate
    %th Email alternate
    %th Notes
    %th
    %th
    %th

  - @stakeholders.each do |stakeholder|
    %tr
      %td= stakeholder.stakeholder_type_id
      %td= stakeholder.company_id
      %td= stakeholder.name
      %td= stakeholder.client_type_id
      %td= stakeholder.name
      %td= stakeholder.address
      %td= stakeholder.city
      %td= stakeholder.state
      %td= stakeholder.zip
      %td= stakeholder.work_phone
      %td= stakeholder.home_phone
      %td= stakeholder.cell_phone
      %td= stakeholder.fax_phone
      %td= stakeholder.email
      %td= stakeholder.address_alternate
      %td= stakeholder.city_alternate
      %td= stakeholder.state_alternate
      %td= stakeholder.zip_alternate
      %td= stakeholder.work_phone_alternate
      %td= stakeholder.home_phone_alternate
      %td= stakeholder.cell_phone_alternate
      %td= stakeholder.fax_phone_alternate
      %td= stakeholder.email_alternate
      %td= stakeholder.notes
      %td= link_to 'Show', stakeholder
      %td= link_to 'Edit', edit_stakeholder_path(stakeholder)
      %td= link_to 'Destroy', stakeholder, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Stakeholder', new_stakeholder_path

app/views/stakeholders/new.html.haml
%h1 New stakeholder

= render 'form'

= link_to 'Back', stakeholders_path

app/views/stakeholders/show.html.haml
%p#notice= notice

%p
  %b Stakeholder type:
  = @stakeholder.stakeholder_type_id
%p
  %b Company:
  = @stakeholder.company_id
%p
  %b Name:
  = @stakeholder.name
%p
  %b Client type:
  = @stakeholder.client_type_id
%p
  %b Name:
  = @stakeholder.name
%p
  %b Address:
  = @stakeholder.address
%p
  %b City:
  = @stakeholder.city
%p
  %b State:
  = @stakeholder.state
%p
  %b Zip:
  = @stakeholder.zip
%p
  %b Work phone:
  = @stakeholder.work_phone
%p
  %b Home phone:
  = @stakeholder.home_phone
%p
  %b Cell phone:
  = @stakeholder.cell_phone
%p
  %b Fax phone:
  = @stakeholder.fax_phone
%p
  %b Email:
  = @stakeholder.email
%p
  %b Address alternate:
  = @stakeholder.address_alternate
%p
  %b City alternate:
  = @stakeholder.city_alternate
%p
  %b State alternate:
  = @stakeholder.state_alternate
%p
  %b Zip alternate:
  = @stakeholder.zip_alternate
%p
  %b Work phone alternate:
  = @stakeholder.work_phone_alternate
%p
  %b Home phone alternate:
  = @stakeholder.home_phone_alternate
%p
  %b Cell phone alternate:
  = @stakeholder.cell_phone_alternate
%p
  %b Fax phone alternate:
  = @stakeholder.fax_phone_alternate
%p
  %b Email alternate:
  = @stakeholder.email_alternate
%p
  %b Notes:
  = @stakeholder.notes

= link_to 'Edit', edit_stakeholder_path(@stakeholder)
\|
= link_to 'Back', stakeholders_path