config/routes.rb
C2earthDev::Application.routes.draw do
  resources :investigation_types

  resources :structure_types

  resources :sites

  resources :faults

  resources :projects

  resources :stakeholder_types

  resources :companies

  resources :stakeholders

  resources :client_types

  resources :project_managers

  resources :phases

  resources :projects
  root :to => 'projects#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :address, :apn, :city, :county, :fault_id, :loc_latitude, :loc_longitude, :loc_page, :number, :structure_type_id, :tombrobox
  has_and_belongs_to_many :structure_types
  belongs_to :fault
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.haml
= form_for @site do |f|
  - if @site.errors.any?
    #error_explanation
      %h2= "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
      %ul
        - @site.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :structure_type_id
    = f.number_field :structure_type_id
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :county
    = f.text_field :county
  .field
    = f.label :loc_page
    = f.text_area :loc_page
  .field
    = f.label :loc_longitude
    = f.text_field :loc_longitude
  .field
    = f.label :loc_latitude
    = f.text_field :loc_latitude
  .field
    = f.label :apn
    = f.text_field :apn
  .field
    = f.label :tombrobox
    = f.text_field :tombrobox
  .field
    = f.label :fault_id
    = f.number_field :fault_id
  .actions
    = f.submit 'Save'

app/views/sites/edit.html.haml
%h1 Editing site

= render 'form'

= link_to 'Show', @site
\|
= link_to 'Back', sites_path

app/views/sites/index.html.haml
%h1 Listing sites

%table
  %tr
    %th Number
    %th Structure type
    %th Address
    %th City
    %th County
    %th Loc page
    %th Loc longitude
    %th Loc latitude
    %th Apn
    %th Tombrobox
    %th Fault
    %th
    %th
    %th

  - @sites.each do |site|
    %tr
      %td= site.number
      %td= site.structure_type_id
      %td= site.address
      %td= site.city
      %td= site.county
      %td= site.loc_page
      %td= site.loc_longitude
      %td= site.loc_latitude
      %td= site.apn
      %td= site.tombrobox
      %td= site.fault_id
      %td= link_to 'Show', site
      %td= link_to 'Edit', edit_site_path(site)
      %td= link_to 'Destroy', site, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Site', new_site_path

app/views/sites/new.html.haml
%h1 New site

= render 'form'

= link_to 'Back', sites_path

app/views/sites/show.html.haml
%p#notice= notice

%p
  %b Number:
  = @site.number
%p
  %b Structure type:
  = @site.structure_type_id
%p
  %b Address:
  = @site.address
%p
  %b City:
  = @site.city
%p
  %b County:
  = @site.county
%p
  %b Loc page:
  = @site.loc_page
%p
  %b Loc longitude:
  = @site.loc_longitude
%p
  %b Loc latitude:
  = @site.loc_latitude
%p
  %b Apn:
  = @site.apn
%p
  %b Tombrobox:
  = @site.tombrobox
%p
  %b Fault:
  = @site.fault_id

= link_to 'Edit', edit_site_path(@site)
\|
= link_to 'Back', sites_path